CryptoPeek/urls.py
from django.urls import path
from . import views
app_name = 'CryptoPeek'
urlpatterns = [
    path('',views.home,name="home"),
    path('cryptopeek/home/',views.home,name="home"),
    path('cryptopeek/favourite/',views.favourite,name="favourite"),
    path('cryptopeek/compare/',views.compare,name="compare"),
    path('cryptopeek/favourite/login/',views.account,name="account"),
    path('cryptopeek/login/',views.account,name="account"),
    path('cryptopeek/delete/<str:crypto_id>/',views.delete,name="delete"),
    path('cryptopeek/register/',views.register,name="register"),
    path('cryptopeek/currencies/', views.currencies, name='currencies'),
    path('cryptopeek/<str:crypto_id>/', views.detail, name='detail')
]

DjangoCrypto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('CryptoPeek.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CryptoPeek/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

CryptoPeek/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

sort_types = (
    ("Default", "Default"),
    ("A-Z", "A-Z"),
    ("Z-A", "Z-A"),
    ("ArrowUp", "Price ↑"),
    ("ArrowDown", "Price ↓"),
    ("ArrowUpMC", "Market Cap ↑"),
    ("ArrowDownMC", "Market Cap ↓"),
    ("ArrowUpPC", "Price Change ↑"),
    ("ArrowDownPC", "Prince Change ↓")
)


class CryptoListForm(forms.Form):
    name = forms.CharField(label="Name:", widget=forms.TextInput(attrs={'placeholder': 'Search by name...'}),
                           required=False)
    from_price = forms.FloatField(label='Beginning price:',
                                  widget=forms.TextInput(attrs={'placeholder': 'Lowest value...'}), required=False)
    to_price = forms.FloatField(label="Highest price:",
                                widget=forms.TextInput(attrs={'placeholder': 'Highest value...'}), required=False)
    sort = forms.ChoiceField(label="Sort:", choices=sort_types, required=False)


class GraphForm(forms.Form):
    date_from = forms.DateField(widget=forms.TextInput(attrs={'placeholder': 'Beginning date(rrrr-mm-dd)'}),
                                required=False)
    date_to = forms.DateField(widget=forms.TextInput(attrs={'placeholder': 'Ending date(rrrr-mm-dd)'}), required=False)


class SignInForm(forms.Form):
    username = forms.CharField(label="Username:")
    password = forms.CharField(label="Password:", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Invalid username or password.")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label='Name:')
    last_name = forms.CharField(label="Surname:")
    email = forms.EmailField(label="Email:")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class CompareForm(forms.Form):
    crypto1 = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Crypto to compare...'}))
    crypto2 = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Crypto to compare...'}))

CryptoPeek/views.py
import datetime
import math
from django.contrib.auth import login, authenticate, logout
from plotly.offline import plot
from plotly.graph_objs import Scatter, Figure, layout, Bar
from django.shortcuts import render, redirect
from requests import get
import pymongo
from .forms import CryptoListForm, SignUpForm, SignInForm, CompareForm

connectionLink = 'mongodb+srv://dgrzesik:cryptopeekdgrzesik@cluster0.r6kad.mongodb.net/CryptoPeek?retryWrites=true&w=majority'
my_client = pymongo.MongoClient(connectionLink)
dbname = my_client['CryptoPeek']
user_favourites = dbname['User_Favourites']


def filter_data(name, input_dict, from_price, to_price, sort_type):
    if from_price:
        input_dict = [x for x in input_dict if x['current_price'] >= from_price]
    if to_price:
        input_dict = [x for x in input_dict if to_price >= x['current_price']]
    if name:
        input_dict = [x for x in input_dict if name.lower() in x['name'].lower()]
    if sort_type == "A-Z":
        input_dict.sort(key=lambda x: x["id"])
    if sort_type == "Z-A":
        input_dict.sort(key=lambda x: x["id"], reverse=True)
    if sort_type == "ArrowDown":
        input_dict.sort(key=lambda x: x["current_price"], reverse=True)
    if sort_type == "ArrowUp":
        input_dict.sort(key=lambda x: x["current_price"])
    if sort_type == "ArrowUpMC":
        input_dict.sort(key=lambda x: x["market_cap"])
    if sort_type == "ArrowDownMC":
        input_dict.sort(key=lambda x: x["market_cap"], reverse=True)
    if sort_type == "ArrowUpPC":
        input_dict.sort(key=lambda x: x["price_change_24h"])
    if sort_type == "ArrowDownPC":
        input_dict.sort(key=lambda x: x["price_change_24h"], reverse=True)
    return input_dict


def getgraphdata(days, crypto_id, all_crypto, graphdata):
    prices = []
    dates = []
    curr_date = datetime.datetime.now() - datetime.timedelta(days)
    first_date = curr_date
    for crypto in all_crypto:
        if crypto["id"] == crypto_id:
            crypto["circulating_supply"] = int(crypto["circulating_supply"])
    if days == 1:
        for value in graphdata["prices"]:
            prices.append(value[1])
            dates.append(curr_date)
            curr_date = curr_date + datetime.timedelta(1 / 24)
    elif days == 365:
        for value in graphdata["prices"]:
            prices.append(value[1])
            dates.append(curr_date)
            curr_date = curr_date + datetime.timedelta(1)
    else:
        for value in graphdata["prices"]:
            prices.append(value[1])
            dates.append(curr_date)
            curr_date = curr_date + datetime.timedelta(1)
    return prices, dates, first_date


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if request.POST['action'] == 'Sign up':
            if form.is_valid():
                user = form.save()
                user.refresh_from_db()
                user.save()
                password = form.cleaned_data['password1']
                user = authenticate(username=user.username, password=password)
                login(request, user)
                user_favourites.insert_one({"username": user.username, "favourites": []})
                return redirect('/cryptopeek/currencies/')
    else:
        form = SignUpForm()
    return render(request, 'CryptoPeek/register.html', {'form': form})


def account(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if request.POST['action'] == 'Sign up':
            return redirect('/cryptopeek/register/')
        if request.POST['action'] == 'Log in':
            if form.is_valid():
                user = form.login(request)
                login(request, user)
                if "favourite" in request.path:
                    return redirect("/cryptopeek/favourite/")
                else:
                    return redirect("/cryptopeek/currencies/")
        if request.POST['action'] == 'Log out':
            logout(request)
            return redirect('/cryptopeek/currencies/')
    else:
        form = SignInForm()
    return render(request, 'CryptoPeek/account.html', {'form': form})


def delete(request, crypto_id):
    user_favourites.update_one({'username': request.user.username}, {"$pull": {'favourites': crypto_id}})
    return redirect('/cryptopeek/favourite')


def compare(request):
    if request.method == 'POST':
        form = CompareForm(request.POST)
        if 'action' in request.POST:
            action = request.POST['action']
        else:
            action = False
        if form.is_valid():
            crypto1 = None
            crypto2 = None
            if action == 'Compare':
                crypto1 = form.cleaned_data["crypto1"]
                crypto2 = form.cleaned_data["crypto2"]
            all_crypto = get(
                'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false').json()
            if crypto1 and crypto2:
                about_crypto1 = [x for x in all_crypto if crypto1.lower() in x['name'].lower()]
                about_crypto2 = [x for x in all_crypto if crypto2.lower() in x['name'].lower()]
                if about_crypto1 != [] and about_crypto2 != []:
                    about_crypto1 = about_crypto1[0]
                    about_crypto2 = about_crypto2[0]
                    month_data_crypto1 = get(
                        'https://api.coingecko.com/api/v3/coins/%s/market_chart?vs_currency=usd&days=%d&interval=daily' % (
                            about_crypto1["id"], 30)).json()
                    prices_crypto1, dates_crypto1, dates_day1_crypto1 = getgraphdata(30, crypto1, all_crypto,
                                                                                     month_data_crypto1)
                    month_data_crypto2 = get(
                        'https://api.coingecko.com/api/v3/coins/%s/market_chart?vs_currency=usd&days=%d&interval=daily' % (
                            about_crypto2["id"], 30)).json()
                    prices_crypto2, dates_crypto2, dates_day1_crypto2 = getgraphdata(30, crypto2, all_crypto,
                                                                                     month_data_crypto2)
                    fig = Figure()
                    fig.add_trace(
                        Scatter(arg=dict(visible=True, name=about_crypto1['name'], x=dates_crypto1, y=prices_crypto1,
                                         mode='markers+lines', opacity=0.8,
                                         marker_color='blue', yaxis="y")))
                    fig.add_trace(
                        Scatter(
                            arg=dict(visible=True, name=about_crypto2['name'], x=dates_crypto2, y=prices_crypto2,
                                     mode='markers+lines', opacity=0.8,
                                     marker_color='red', yaxis="y2")))
                    fig.add_trace(
                        Bar(arg=dict(visible=False, name=about_crypto1['name'], x=dates_crypto1, y=prices_crypto1,
                                     opacity=0.8,
                                     marker_color='blue', yaxis="y")))
                    fig.add_trace(
                        Bar(
                            arg=dict(visible=False, name=about_crypto2['name'], x=dates_crypto2, y=prices_crypto2,
                                     opacity=0.8,
                                     marker_color='red', yaxis="y2")))

                    fig.update_layout(xaxis_title="Dates", width=1100, height=600,
                                      title="Last month's price change comparison",
                                      yaxis=dict(title=about_crypto1['name'], titlefont=dict(color="blue"),
                                                 tickfont=dict(color="blue")),
                                      yaxis2=dict(title=about_crypto2['name'], titlefont=dict(color="red"),
                                                  tickfont=dict(color="red"), anchor="x", automargin=True,
                                                  overlaying="y",
                                                  side="right"),
                                      updatemenus=[layout.Updatemenu(
                                          active=0,
                                          buttons=[dict(label="Compare",
                                                        method='update',
                                                        args=[{'visible': [True, True, False, False]},
                                                              {"yaxis.visible": True, "yaxis2.visible": True,
                                                               'title': "Last month's price change comparison",
                                                               "yaxis2.side": "right", "yaxis.autorange": True,
                                                               "yaxis2.autorange": True}]),
                                                   dict(label=about_crypto1['name'],
                                                        method='update',
                                                        args=[{'visible': [False, False, True, False]},
                                                              {"yaxis.visible": True, "yaxis2.visible": False,
                                                               'title': about_crypto1['name'],
                                                               "yaxis2.side": "right",
                                                               "yaxis.range": [
                                                                   min(prices_crypto1) - (0.01 * min(prices_crypto1)),
                                                                   max(prices_crypto1) + (
                                                                           0.01 * min(prices_crypto1))],

CryptoPeek/templates/CryptoPeek/account.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/CryptoPeek/account.css' %}">
<div class="navbar">
    <a id="curr" href="{% url 'CryptoPeek:home' %}"><div class="logo">CryptoPeek</div></a>
    <div class="options">
        <a id="curr" href="{% url 'CryptoPeek:home' %}"><div id="opt">Home</div></a>
        <a id="curr" href="{% url 'CryptoPeek:currencies' %}"><div id="opt">Currencies</div></a>
        <a id="curr" href="{% url 'CryptoPeek:compare' %}"><div id="opt">Compare</div></a>
        <a id="curr" href="{% url 'CryptoPeek:favourite' %}"><div id="opt">Favourite</div></a>
    </div>
</div>
<div class="slogan">
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            <input id="nameinput" type="submit" name='action' value="Log out">
        </form>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input id="nameinput" type="submit" name='action' value="Log in">
            <a id="curr" href="{% url 'CryptoPeek:register' %}"><button id="nameinput" type="button">Sign up</button></a>
        </form>
    {% endif %}
</div>

CryptoPeek/templates/CryptoPeek/currencies.html
<!doctype html>
{% load static %}
{% load CryptoPeek_tags %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static '/CryptoPeek/currencies.css' %}">
<style>
        * {
            color: black;
        }

        img {
            height: 4rem;
            width: 4rem;
        }
</style>

<nav class="navbar">
    <a id="curr" href="{% url 'CryptoPeek:home' %}"><div class="logo">CryptoPeek</div></a>
    <div class="options">
        {% if user.is_authenticated %}
            <div id="optnohov">{{ user.username }}</div>
        {% endif %}
        <a id="curr" href="{% url 'CryptoPeek:home' %}"><div id="opt">Home</div></a>
        <a id="curr" href="{% url 'CryptoPeek:currencies' %}"><div id="currentopt">Currencies</div></a>
        <a id="curr" href="{% url 'CryptoPeek:compare' %}"><div id="opt">Compare</div></a>
        <a id="curr" href="{% url 'CryptoPeek:favourite' %}"><div id="opt">Favourite</div></a>
        {% if user.is_authenticated %}
            <div id="opt">
                <form method="post">
                    {% csrf_token %}
                    <input id="nameinput" type="submit" name='action' value="Log out">
                </form>
            </div>
        {% else %}
            <a id="curr" href="{% url 'CryptoPeek:account' %}"><div id="opt">Log in</div></a>
        {% endif %}
    </div>
</nav>

<div class="search">
            <form action='' method="POST">
                {% csrf_token %}
                {{ form }}
                <input id="nameinput1" type="submit" name="action" value="Search">
            </form>
</div>
<section>
        <div class="container py-5">
            <div class="table-responsive text-white">
                <table class="table table-striped text-center table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Crypto Currency</th>
                            <th scope="col">Current Price USD</th>
                            <th scope="col">Price change (24h)</th>
                            <th scope="col">Market Cap</th>
                            <th scope="col">Details</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        {% for i in all_crypto %}
                        <tr>
                            <td><img src="{{i.image}}" alt="image"> <h5>{{i.name}}/{{i.symbol}} </h5></td>
                            <td><h5 style="height: 90px;line-height: 90px">${{i.current_price}}</h5></td>
                                {% if i.price_change_24h > 0 %}
                                    <td><h5 style="display: inline" >$</h5><h5 style = "color:lightgreen;height: 90px;line-height: 90px; display: inline" >{{i.price_change_24h|round_small_values }}</h5></td>
                                {% else %}
                                    <td><h5 style="display: inline" >$</h5><h5 style = "color:indianred;height: 90px;line-height: 90px; display: inline" >{{i.price_change_24h|round_small_values }}</h5></td>
                                {% endif %}
                            <td><h5 style="height: 90px;line-height: 90px">${{i.market_cap | round_large_values}}</h5></td>
                            <td><a id="link" href="{% url 'CryptoPeek:detail' i.id %}"><h5 class="more">More</h5></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
</section>

CryptoPeek/templates/CryptoPeek/details.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static '/CryptoPeek/details.css' %}">
<nav class="navbar">
    <a id="curr" href="{% url 'CryptoPeek:home' %}"><div class="logo">CryptoPeek</div></a>
    <div class="options">
        {% if user.is_authenticated %}
            <div id="optnohov">{{ user.username }}</div>
        {% endif %}
        <a id="curr" href="{% url 'CryptoPeek:home' %}"><div id="opt">Home</div></a>
        <a id="curr" href="{% url 'CryptoPeek:currencies' %}"><div id="opt">Currencies</div></a>
        <a id="curr" href="{% url 'CryptoPeek:compare' %}"><div id="opt">Compare</div></a>
        <a id="curr" href="{% url 'CryptoPeek:favourite' %}"><div id="opt">Favourite</div></a>
        {% if user.is_authenticated %}
            <div id="opt">
                <form method="post">
                    {% csrf_token %}
                    <input id="nameinput" type="submit" name='action' value="Log out">
                </form>
            </div>
        {% else %}
            <a id="curr" href="{% url 'CryptoPeek:account' %}"><div id="opt">Log in</div></a>
        {% endif %}
    </div>
</nav>

<div class="container">

    <div class="actions">
        <form action='' method="POST">
            {% csrf_token %}
            {% if not liked_status %}
                <input class='fav' type="submit" name="like" value="🤍">
            {% else %}
                <input class='fav' type="submit" name="like" value="❤️">
            {% endif %}
        </form>
        <a id="link" href="{% url 'CryptoPeek:currencies' %}"><div class="return">Return to currencies</div></a>
    </div>
    <div class="name">{{ curr_crypto.name }}</div>
    <div class="valueinfo">
        <div class="image">
            {% autoescape off %}
                {{ plot_div }}
            {% endautoescape %}
        </div>
        <div class="valuetable">
            {% for crypto in all_crypto %}
                {% if crypto.id == curr_crypto.id %}
                    <div class="numberstop" id="currprice">Current price: {{ crypto.current_price}} USD</div>
                    <div class="numbers" id="pricechange24h">Price change(24h): {{ crypto.price_change_24h }} USD ({{ crypto.price_change_percentage_24h }}%)</div>
                    <div class="numbers" id="marketcap">Market cap: {{ crypto.market_cap }}</div>
                    <div class="numbers" id="highest">Highest price: {{ crypto.high_24h }} USD</div>
                    <div class="numbers" id="lowest">Lowest price: {{ crypto.low_24h }} USD</div>
                    <div class="numbers"  id="circulating">Circulating: {{ crypto.circulating_supply }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="description"><div class="header">All about {{ curr_crypto.name }}</div>{{curr_crypto.description.en}}</div>
</div>

CryptoPeek/templates/CryptoPeek/favourite.html
<!doctype html>
{% load static %}
{% load CryptoPeek_tags %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static '/CryptoPeek/favourite.css' %}">
<style>
        * {
            color: black;
        }

        img {
            height: 4rem;
            width: 4rem;
        }
</style>

<nav class="navbar">
    <a id="curr" href="{% url 'CryptoPeek:home' %}"><div class="logo">CryptoPeek</div></a>
    <div class="options">
        {% if user.is_authenticated %}
            <div id="optnohov">{{ user.username }}</div>
        {% endif %}
        <a id="curr" href="{% url 'CryptoPeek:home' %}"><div id="opt">Home</div></a>
        <a id="curr" href="{% url 'CryptoPeek:currencies' %}"><div id="opt">Currencies</div></a>
        <a id="curr" href="{% url 'CryptoPeek:compare' %}"><div id="opt">Compare</div></a>
        <a id="curr" href="{% url 'CryptoPeek:favourite' %}"><div id="currentopt">Favourite</div></a>
        {% if user.is_authenticated %}
            <div id="opt">
                <form method="post">
                    {% csrf_token %}
                    <input id="nameinput" type="submit" name='action' value="Log out">
                </form>
            </div>
        {% else %}
            <a id="curr" href="{% url 'CryptoPeek:account' %}"><div id="opt">Log in</div></a>
        {% endif %}
    </div>
</nav>

<div class="search">
            <form action='' method="POST">
                {% csrf_token %}
                {{ form }}
                <input id="nameinput1" type="submit" name='action' value="Search">
            </form>
</div>
<section>
        <div class="container py-5">
            <div class="table-responsive text-white">
                <table class="table table-striped text-center table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Crypto Currency</th>
                            <th scope="col">Current Price USD</th>
                            <th scope="col">Price change (24h)</th>
                            <th scope="col">Market Cap</th>
                            <th scope="col">Details</th>
                            <th scope="col">Unfollow</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        {% for i in all_crypto %}
                        <tr>
                            <td><img src="{{i.image}}" alt="image"> <h5>{{i.name}}/{{i.symbol}} </h5></td>
                            <td><h5 style="height: 90px;line-height: 90px">${{i.current_price}}</h5></td>
                                {% if i.price_change_24h > 0 %}
                                    <td><h5 style="display: inline" >$</h5><h5 style = "color:lightgreen;height: 90px;line-height: 90px; display: inline" >{{i.price_change_24h }}</h5></td>
                                {% else %}
                                    <td><h5 style="display: inline" >$</h5><h5 style = "color:indianred;height: 90px;line-height: 90px; display: inline" >{{i.price_change_24h }}</h5></td>
                                {% endif %}
                            <td><h5 style="height: 90px;line-height: 90px">${{i.market_cap | round_large_values}}</h5></td>
                            <td><a id="link" href="{% url 'CryptoPeek:detail' i.id %}"><h5 class="more">More</h5></a></td>
                            <td>
                                 <a id="link" href="{% url 'CryptoPeek:delete' i.id %}">
                                     <div class="fav" >✖️</div>
                                 </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
</section>

CryptoPeek/templates/CryptoPeek/home.html
<!doctype html>
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static '/CryptoPeek/home.css' %}">
<div class="navbar">
    <a id="curr" href="{% url 'CryptoPeek:home' %}"><div class="logo">CryptoPeek</div></a>
    <div class="options">
        {% if user.is_authenticated %}
            <div id="optnohov">{{ user.username }}</div>
        {% endif %}
        <a id="curr" href="{% url 'CryptoPeek:home' %}"><div id="currentopt">Home</div></a>
        <a id="curr" href="{% url 'CryptoPeek:currencies' %}"><div id="opt">Currencies</div></a>
        <a id="curr" href="{% url 'CryptoPeek:compare' %}"><div id="opt">Compare</div></a>
        <a id="curr" href="{% url 'CryptoPeek:favourite' %}"><div id="opt">Favourite</div></a>
        {% if user.is_authenticated %}
            <div id="opt">
                <form method="post">
                    {% csrf_token %}
                    <input id="nameinput" type="submit" name='action' value="Log out">
                </form>
            </div>
        {% else %}
            <a id="curr" href="{% url 'CryptoPeek:account' %}"><div id="opt">Log in</div></a>
        {% endif %}
    </div>

</div>
<div class="container">
    <div class="slogan">
        <div id="text">
            Your dad's favourite place to satisfy his gambling addiction :D
        </div>
    </div>
       <div class="top">
           <a id="link" href="{% url 'CryptoPeek:detail' highest_profit_data.id %}">
               {% for crypto in all_crypto %}
                   {% if crypto.id == highest_profit_data.id %}
                       <div class="name">
                       <div class="nohoveron">Highest profit in last 24h: {{ highest_profit_data.name }} ({{crypto.price_change_percentage_24h}}%)</div>
                        <div class="hoveron">Learn more!</div>
                       </div>
                   {% endif %}
               {% endfor %}
           </a>
           <div class="graph">
                {% autoescape off %}
                    {{ plot_div_highest_profit }}
                {% endautoescape %}
           </div>
       </div>
</div>
<div class="container">
    <div class="slogan">
        <div id="text">
            I don't know why does this interest you, but here you go nerd...
        </div>
    </div>
       <div class="top">
       <a id="link" href="{% url 'CryptoPeek:detail' lowest_profit_data.id %}">
           {% for crypto in all_crypto %}
               {% if crypto.id == lowest_profit_data.id %}
                    <div class="name">
                        <div class="nohoveron">Lowest profit in last 24h: {{ lowest_profit_data.name }} ({{crypto.price_change_percentage_24h}}%)</div>
                        <div class="hoveron">Learn more!</div>
                    </div>
               {% endif %}
           {% endfor %}
       </a>
                <div class="graph">
                {% autoescape off %}
                    {{ plot_div_lowest_profit }}
                {% endautoescape %}</div>
       </div>
</div>